server.port=8082
spring.application.name=catalog-service

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/catalog_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración del Pool de Conexiones
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Clave JWT compartida
jwt.secret=${JWT_SECRET:8Zz5twkAG5aBqY6A1c8fE2gH4jK6mN8pQ0rS2tU4vW6xY8z0aB2cD4eF6gH8jK0m}